[project]
name = "pokemon-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-groq>=0.3.7",
    "mcp[cli]>=1.13.1",
]
